import { useCallback,useEffect,useState } from 'react';
import { Alert,FlatList,SafeAreaView,ScrollView,StyleSheet,Text,View } from 'react-native';
import { router } from 'expo-router';
import { Button,Card,EmptyState,Input,Loading,confirm } from '@/components/ui';
import { spacing } from '@/constants/theme'; import { useThemedStyles } from '@/hooks/use-themed-styles'; import { b2bService } from '@/services/b2b.service'; import { apiError } from '@/services/api'; import { authService } from '@/services/auth.service'; import { storage } from '@/services/storage'; import { useAuth } from '@/hooks/use-auth';
type Section='dashboard'|'users'|'providers'|'clients'|'requests'|'products'|'logs'|'config'|'security';
const labels:Record<Section,string>={dashboard:'Dashboard',users:'Usuarios',providers:'Proveedores',clients:'Clientes',requests:'Solicitudes',products:'Productos',logs:'Logs',config:'Configuraciones',security:'Seguridad'};const list=(v:any)=>Array.isArray(v)?v:Array.isArray(v?.data)?v.data:[];const state=(v:any)=>String(v||'').trim().toUpperCase();
type ConfigDraft={id?:number;clave:string;valor:string;tipo:string;estado:string};
type ManualBlock={tipo:'USUARIO'|'IP';value:string};
export default function AdminOperations({initialSection='dashboard'}:{initialSection?:Section}){
  const {session}=useAuth();
  const styles=useStyles(),[section,setSection]=useState<Section>(initialSection),[items,setItems]=useState<any[]>([]),[dash,setDash]=useState<any>(null),[loading,setLoading]=useState(true);
  const [editing,setEditing]=useState<ConfigDraft|null>(null),[saving,setSaving]=useState(false);
  const [manualBlock,setManualBlock]=useState<ManualBlock|null>(null),[blockBusy,setBlockBusy]=useState<string|null>(null);
  useEffect(()=>setSection(initialSection),[initialSection]);
  const load=useCallback(async()=>{setLoading(true);try{if(section==='dashboard'){const r=await Promise.allSettled([b2bService.adminUsers(),b2bService.adminProviders(),b2bService.adminRequests(),b2bService.adminLogs()]);const v=r.map(x=>x.status==='fulfilled'?list(x.value):[]);setDash({users:v[0],providers:v[1],requests:v[2],logs:v[3]});return;}let data:any=[];if(section==='users'||section==='clients'){const users=list(await b2bService.adminUsers());data=users.filter((u:any)=>section==='clients'?state(u.rol)==='CLIENTE':state(u.rol)!=='CLIENTE');}else if(section==='providers')data=await b2bService.adminProviders();else if(section==='requests')data=await b2bService.adminRequests();else if(section==='products')data=await b2bService.adminProducts();else if(section==='logs')data=await b2bService.adminLogs();else if(section==='config')data=await b2bService.config();else{const [u,ips]=await Promise.all([b2bService.securityUsers(),b2bService.securityIps()]);data=[...list(u),...list(ips)];}setItems(list(data));}catch(e){setItems([]);Alert.alert('No se pudo cargar',apiError(e));}finally{setLoading(false);}},[section]);
  useEffect(()=>{void load();},[load]);
  const requestMfa=async():Promise<string|null>=>{const existing=await storage.getMfaAction();if(existing)return existing;try{const flow=await authService.startMfaChallenge(session?.email||'','ADMIN_ACTION','email');await storage.setMfa({email:session?.email||'',tempToken:flow.tempToken,purpose:'ADMIN_ACTION',expiresInSeconds:flow.expiresInSeconds,method:'email'});Alert.alert('Verificación requerida','Confirma el código MFA y vuelve a intentarlo.');router.push('/mfa');}catch(e){Alert.alert('No se pudo iniciar la verificación',apiError(e));}return null;};
  const saveConfig=async()=>{if(!editing||!editing.clave.trim())return Alert.alert('Clave requerida','Ingresa una clave para la variable.');setSaving(true);try{const token=await requestMfa();if(!token){setSaving(false);return;}const body={clave:editing.clave.trim(),valor:editing.valor.trim(),tipo:editing.tipo.trim()||'KEY',estado:editing.estado.trim()||'ACTIVO'};if(editing.id)await b2bService.updateConfig(editing.id,body,token);else await b2bService.createConfig(body,token);await storage.clearMfaAction();setEditing(null);await load();Alert.alert(editing.id?'Configuración actualizada':'Variable creada');}catch(e){Alert.alert('No se pudo guardar',apiError(e));}finally{setSaving(false);}};
  const deleteConfig=(item:any)=>confirm('Eliminar variable',`¿Deseas eliminar ${item.clave}?`,async()=>{try{const token=await requestMfa();if(!token)return;await b2bService.deleteConfig(item.id,token);await storage.clearMfaAction();await load();Alert.alert('Variable eliminada');}catch(e){Alert.alert('No se pudo eliminar',apiError(e));}});
  const testConfig=async(item:any)=>{if(!item.testeable)return;try{const result=await b2bService.testConfig(item.id);const ok=String(result).trim().toUpperCase()==='OK';setItems(current=>current.map((x:any)=>x.id===item.id?{...x,estado:ok?'ACTIVO':'INACTIVO'}:x));Alert.alert(ok?'Conexión exitosa':'Conexión fallida');}catch(e){setItems(current=>current.map((x:any)=>x.id===item.id?{...x,estado:'INACTIVO'}:x));Alert.alert('No se pudo probar la conexión',apiError(e));}};
  const unblock=(item:any)=>confirm('Desbloquear registro',`¿Deseas desbloquear ${item.identificador}?`,async()=>{setBlockBusy(item.identificador);try{const token=await requestMfa();if(!token)return;await b2bService.securityAction(item.tipo==='IP'?'IP':'USUARIO','desbloquear',item.identificador,token);await storage.clearMfaAction();await load();Alert.alert('Registro desbloqueado');}catch(e){Alert.alert('No se pudo desbloquear',apiError(e));}finally{setBlockBusy(null);}});
  const submitManualBlock=async()=>{if(!manualBlock||!manualBlock.value.trim())return Alert.alert('Dato requerido',`Ingresa ${manualBlock?.tipo==='IP'?'la IP':'el correo'} a bloquear.`);setBlockBusy('manual');try{const token=await requestMfa();if(!token){setBlockBusy(null);return;}await b2bService.securityAction(manualBlock.tipo,'bloquear',manualBlock.value.trim(),token);await storage.clearMfaAction();setManualBlock(null);await load();Alert.alert('Registro bloqueado');}catch(e){Alert.alert('No se pudo bloquear',apiError(e));}finally{setBlockBusy(null);}};
  if(loading)return <Loading/>;
  const users=dash?.users||[],providers=dash?.providers||[],requests=dash?.requests||[],active=users.filter((u:any)=>state(u.estado)==='ACTIVO'),open=requests.filter((r:any)=>!['CANCELADA','COMPLETADA','ENTREGADA'].includes(state(r.estado))),total=requests.reduce((n:number,r:any)=>n+Number(r.total||0),0);
  return <SafeAreaView style={styles.root}><Text style={styles.title}>{labels[section]}</Text><ScrollView horizontal contentContainerStyle={styles.tabs}>{(Object.keys(labels)as Section[]).map(x=><Text key={x} onPress={()=>setSection(x)} style={[styles.tab,section===x&&styles.active]}>{labels[x]}</Text>)}</ScrollView>
  {section==='dashboard'?<ScrollView contentContainerStyle={styles.list}><View style={styles.grid}><Metric styles={styles} value={active.length||users.length} label="Usuarios activos"/><Metric styles={styles} value={providers.length} label="Proveedores"/><Metric styles={styles} value={requests.length} label="Solicitudes RFQ"/><Metric styles={styles} value={`S/ ${total.toFixed(2)}`} label="Volumen transaccional"/></View><Card><Text style={styles.name}>Indicadores operativos</Text><Text style={styles.detail}>{open.length} solicitudes en curso</Text><Text style={styles.detail}>{requests.length-open.length} solicitudes cerradas</Text></Card><Card><Text style={styles.name}>Actividad reciente</Text>{dash?.logs?.length?dash.logs.slice(0,5).map((x:any,i:number)=><Text key={i} style={styles.detail}>{x.accion||x.modulo||'Actividad'}: {x.descripcion||x.fecha||'Sin detalle'}</Text>):<Text style={styles.detail}>No hay logs recientes disponibles.</Text>}</Card></ScrollView>
  :section==='config'?<ScrollView contentContainerStyle={styles.list}>
    {editing?<Card><Text style={styles.name}>{editing.id?`Editar ${editing.clave}`:'Nueva variable'}</Text><Input label="Clave" value={editing.clave} onChangeText={v=>setEditing(x=>x&&({...x,clave:v}))} autoCapitalize="characters" editable={!editing.id}/><Input label="Valor" value={editing.valor} onChangeText={v=>setEditing(x=>x&&({...x,valor:v}))}/><Input label="Tipo" value={editing.tipo} onChangeText={v=>setEditing(x=>x&&({...x,tipo:v}))} placeholder="KEY, URL o CONFIG"/><Input label="Estado" value={editing.estado} onChangeText={v=>setEditing(x=>x&&({...x,estado:v}))} placeholder="ACTIVO o INACTIVO" autoCapitalize="characters"/><Button title="Guardar" onPress={saveConfig} loading={saving}/><Button title="Cancelar" variant="secondary" onPress={()=>setEditing(null)}/></Card>
    :<Button title="+ Nueva variable" onPress={()=>setEditing({clave:'',valor:'',tipo:'KEY',estado:'ACTIVO'})}/>}
    {items.length?items.map((item:any,i:number)=><Card key={item.id||i}><Text style={styles.name}>{item.clave}</Text><Text style={styles.detail}>{item.valor||'-'}</Text><Text style={styles.detail}>Tipo: {item.tipo||'-'} · Estado: {item.estado||'-'}</Text><View style={styles.row}><Button title="Editar" variant="secondary" onPress={()=>setEditing({id:item.id,clave:item.clave,valor:item.valor||'',tipo:item.tipo||'KEY',estado:item.estado||'ACTIVO'})}/>{item.testeable?<Button title="Probar" variant="secondary" onPress={()=>void testConfig(item)}/>:null}<Button title="Eliminar" variant="danger" onPress={()=>deleteConfig(item)}/></View></Card>):<EmptyState title="Sin configuraciones" detail="Agrega una variable para comenzar."/>}
  </ScrollView>
  :section==='security'?<ScrollView contentContainerStyle={styles.list}>
    {manualBlock?<Card><Text style={styles.name}>Bloquear {manualBlock.tipo==='IP'?'IP':'usuario'}</Text><Input label={manualBlock.tipo==='IP'?'Dirección IP':'Correo del usuario'} value={manualBlock.value} onChangeText={v=>setManualBlock(x=>x&&({...x,value:v}))} autoCapitalize="none"/><Button title="Bloquear" variant="danger" onPress={submitManualBlock} loading={blockBusy==='manual'}/><Button title="Cancelar" variant="secondary" onPress={()=>setManualBlock(null)}/></Card>
    :<View style={styles.row}><Button title="Bloquear usuario" variant="secondary" onPress={()=>setManualBlock({tipo:'USUARIO',value:''})}/><Button title="Bloquear IP" variant="secondary" onPress={()=>setManualBlock({tipo:'IP',value:''})}/></View>}
    {items.length?items.map((item:any,i:number)=><Card key={item.idBloqueo||i}><Text style={styles.name}>{item.identificador}</Text><Text style={styles.detail}>{item.tipo==='IP'?'Dirección IP':item.nombreUsuario||item.correoUsuario||'Usuario'} · {item.intentosFallidos||0} intentos fallidos</Text><Text style={styles.detail}>Motivo: {item.motivo||'-'}</Text><Text style={styles.detail}>Bloqueado: {item.fechaBloqueo?new Date(item.fechaBloqueo).toLocaleString('es-PE'):'-'}</Text><Button title="Desbloquear" onPress={()=>unblock(item)} loading={blockBusy===item.identificador}/></Card>):<EmptyState title="Sin bloqueos" detail="No hay usuarios ni IPs bloqueados."/>}
  </ScrollView>
  :<FlatList data={items} keyExtractor={(x,i)=>String(x.idUsuario||x.idProveedor||x.idSolicitud||x.idProducto||x.id||i)} contentContainerStyle={styles.list} ListEmptyComponent={<EmptyState title="Sin registros" detail="No hay información disponible."/>} renderItem={({item})=><Card><Text style={styles.name}>{item.producto||item.nombre||item.razonSocial||item.nombreEmpresa||`${item.nombres||''} ${item.apellidos||''}`.trim()||item.accion||item.modulo||'Registro'}</Text><Text style={styles.detail}>{item.correo||item.rol||item.estado||item.descripcion||item.valor||'-'}</Text></Card>}/>}
  </SafeAreaView>;
}
function Metric({styles,value,label}:any){return <Card style={styles.metric}><Text style={styles.number}>{value}</Text><Text style={styles.detail}>{label}</Text></Card>};const useStyles=()=>useThemedStyles(c=>StyleSheet.create({root:{flex:1,backgroundColor:c.bg},title:{fontSize:24,fontWeight:'800',color:c.text,padding:spacing.md,paddingBottom:0},tabs:{paddingHorizontal:spacing.md,gap:12},tab:{paddingVertical:12,color:c.muted,fontWeight:'700'},active:{color:c.accentText,borderBottomWidth:2,borderColor:c.primary},list:{padding:spacing.md,gap:12},grid:{flexDirection:'row',flexWrap:'wrap',gap:10},metric:{width:'47%',minHeight:100,justifyContent:'center'},number:{fontSize:22,fontWeight:'800',color:c.accentText},name:{fontSize:16,fontWeight:'800',color:c.text},detail:{color:c.muted,lineHeight:20},row:{flexDirection:'row',gap:8,flexWrap:'wrap'}}));
