import { useCallback, useEffect, useState } from 'react';
import { Alert, FlatList, StyleSheet, Text, View } from 'react-native';
import { router } from 'expo-router';
import { Button, Card, EmptyState, Loading } from '@/components/ui';
import { spacing } from '@/constants/theme';
import { useThemedStyles } from '@/hooks/use-themed-styles';
import { b2bService } from '@/services/b2b.service'; import { apiError } from '@/services/api';
export default function TopProviders(){ const [items,setItems]=useState<Record<string,any>[]|null>(null); const styles=useStyles(); const load=useCallback(async()=>{try{setItems(await b2bService.topProviders());}catch(e){Alert.alert('No se pudo cargar el ranking',apiError(e));setItems([]);}},[]); useEffect(()=>{void load();},[load]); if(!items)return <Loading/>; return <FlatList style={styles.root} contentContainerStyle={styles.list} data={items} keyExtractor={(item,i)=>String(item.idProveedor||i)} ListHeaderComponent={<><Text style={styles.title}>Top Proveedores</Text><Text style={styles.subtitle}>Ranking comercial basado en cumplimiento, satisfacción y operaciones completadas.</Text></>} ListEmptyComponent={<EmptyState title="Sin proveedores para mostrar" detail="El ranking aparecerá cuando existan indicadores disponibles."/>} renderItem={({item,index})=><Card><View style={styles.head}><View style={styles.rank}><Text style={styles.rankText}>#{index+1}</Text></View><View style={styles.company}><Text style={styles.name}>{item.razonSocial||'Proveedor'}</Text><Text style={styles.meta}>{item.categoriaPrincipal||'Proveedor B2B'} {item.verificado?' · Verificado':''}</Text></View><Text style={styles.score}>{Number(item.scoreGeneral||0).toFixed(0)}<Text style={styles.scoreUnit}>/100</Text></Text></View><Text style={styles.description}>{item.descripcion||'Indicadores comerciales y reputación disponibles para este proveedor.'}</Text><View style={styles.metrics}><Text style={styles.metric}>★ {Number(item.satisfaccion||0).toFixed(0)}% satisfacción</Text><Text style={styles.metric}>✓ {Number(item.cumplimiento||0).toFixed(0)}% cumplimiento</Text><Text style={styles.metric}>{item.totalResenas||0} reseñas</Text></View><Button title="Ver reseñas por producto" variant="secondary" onPress={()=>router.push('/(tabs)/catalog')}/></Card>}/>; }
const useStyles=()=>useThemedStyles(c=>StyleSheet.create({root:{flex:1,backgroundColor:c.bg},list:{padding:spacing.md,gap:12},title:{fontSize:26,fontWeight:'800',color:c.text},subtitle:{color:c.muted,lineHeight:20,marginBottom:4},head:{flexDirection:'row',alignItems:'center',gap:10},rank:{width:42,height:42,borderRadius:21,backgroundColor:c.surfaceSoft,alignItems:'center',justifyContent:'center',borderWidth:1,borderColor:c.border},rankText:{color:c.accentText,fontWeight:'800'},company:{flex:1},name:{fontSize:17,fontWeight:'800',color:c.text},meta:{fontSize:12,color:c.muted},score:{color:c.accentText,fontSize:21,fontWeight:'800'},scoreUnit:{fontSize:12,color:c.muted},description:{color:c.textSoft,lineHeight:19},metrics:{flexDirection:'row',flexWrap:'wrap',gap:8},metric:{fontSize:12,color:c.successText,backgroundColor:c.surfaceSoft,paddingHorizontal:8,paddingVertical:5,borderRadius:8}}));
