import { useCallback, useEffect, useMemo, useState } from 'react';
import { Alert, SafeAreaView, ScrollView, StyleSheet, Text, View } from 'react-native';
import * as DocumentPicker from 'expo-document-picker';
import { router, useLocalSearchParams } from 'expo-router';
import { Button, Card, Input, Loading } from '@/components/ui';
import { spacing } from '@/constants/theme';
import { useThemedStyles } from '@/hooks/use-themed-styles';
import { apiError } from '@/services/api';
import { b2bService } from '@/services/b2b.service';

const normalize = (value: unknown) => String(value || '').trim().toUpperCase().replace(/\s+/g, '_');
const label = (value: unknown) => String(value || 'En proceso').replaceAll('_', ' ');

export default function RequestTracking() {
  const { id } = useLocalSearchParams<{ id: string }>(); const styles = useStyles();
  const [tracking, setTracking] = useState<any>(null); const [loading, setLoading] = useState(true);
  const [description, setDescription] = useState(''); const [type, setType] = useState(''); const [evidence, setEvidence] = useState<any>(null); const [submitting, setSubmitting] = useState(false);
  const load = useCallback(async () => { setLoading(true); try { setTracking(await b2bService.requestTracking(Number(id))); } catch (e) { Alert.alert('No se pudo cargar el seguimiento', apiError(e)); } finally { setLoading(false); } }, [id]);
  useEffect(() => { void load(); }, [load]);
  const types = useMemo(() => { const current = normalize(tracking?.estado); const timeline = Array.isArray(tracking?.timeline) ? tracking.timeline : []; const states = timeline.map((x: any) => normalize(x.estado)); const terminal = ['CANCELADA','RECHAZADA','ENTREGADA','COMPLETADA'].includes(current); const next: string[] = []; if (states.includes('CANCELADA') || ['CANCELADA','RECHAZADA'].includes(current)) next.push('CANCELACION'); if (states.some((x: string) => ['ENTREGADA','COMPLETADA'].includes(x)) || (!terminal && ['EN_PREPARACION','PREPARACION','EN_CAMINO','ENVIADO','PROCESANDO','ACEPTADA','PENDIENTE','SOLICITADA'].includes(current))) next.push('ENTREGA_INCOMPLETA'); const date = tracking?.fechaLimiteEntrega || tracking?.fechaEntregaPrometida || tracking?.fechaEntregaEstimada; if (!terminal && date && Date.now() > new Date(date).getTime()) next.push('DEMORA'); return next; }, [tracking]);
  useEffect(() => { if (!types.includes(type)) setType(types[0] || ''); }, [types, type]);
  const chooseEvidence = async () => { const result = await DocumentPicker.getDocumentAsync({ type:['image/*','application/pdf'], copyToCacheDirectory:true }); if (!result.canceled) setEvidence(result.assets[0]); };
  const submit = async () => { if (!type || !description.trim()) return Alert.alert('Completa el reclamo', 'Selecciona un tipo permitido y describe el inconveniente.'); setSubmitting(true); try { const body = new FormData(); body.append('idSolicitud', String(id)); body.append('tipo', type); body.append('descripcion', description.trim()); if (evidence) body.append('evidencia', { uri:evidence.uri, name:evidence.name || 'evidencia', type:evidence.mimeType || 'application/octet-stream' } as any); await b2bService.createDelayClaim(body); setDescription(''); setEvidence(null); Alert.alert('Reclamo enviado'); } catch (e) { Alert.alert('No se pudo enviar el reclamo', apiError(e)); } finally { setSubmitting(false); } };
  if (loading) return <Loading/>;
  return <SafeAreaView style={styles.root}><ScrollView contentContainerStyle={styles.content}><Text style={styles.title}>Seguimiento de solicitud</Text><Card><Text style={styles.state}>{label(tracking?.estado)}</Text><Text style={styles.text}>Solicitud RFQ-{String(tracking?.idSolicitud || id).padStart(4,'0')}</Text><Text style={styles.provider}>{tracking?.proveedor || 'Proveedor pendiente'}</Text><Text style={styles.text}>Total: {tracking?.total == null ? '—' : `S/ ${Number(tracking.total).toFixed(2)}`}</Text><Text style={styles.text}>Dirección: {tracking?.direccion || tracking?.direccionEnvio || 'Pendiente'}</Text></Card><Card><Text style={styles.section}>Progreso</Text>{Array.isArray(tracking?.timeline) && tracking.timeline.length ? tracking.timeline.map((step:any,index:number) => <View key={`${step.fecha || index}`} style={styles.step}><Text style={styles.stepTitle}>{label(step.estado || step.titulo)}</Text><Text style={styles.text}>{step.descripcion || ''}</Text></View>) : <Text style={styles.text}>Aún no hay eventos de seguimiento.</Text>}</Card>{types.length ? <Card><Text style={styles.section}>Crear reclamo</Text><Text style={styles.text}>Solo se ofrecen los tipos habilitados por el estado real de la solicitud.</Text>{types.map(item => <Button key={item} title={item.replaceAll('_',' ')} variant={type === item ? 'primary' : 'secondary'} onPress={() => setType(item)}/>)}<Input label="Descripción *" multiline value={description} onChangeText={setDescription} placeholder="Describe el inconveniente"/><Button title={evidence ? `Evidencia: ${evidence.name}` : 'Adjuntar evidencia (imagen o PDF)'} variant="secondary" onPress={() => void chooseEvidence()}/><Button title="Enviar reclamo" onPress={() => void submit()} loading={submitting}/></Card> : null}<Button title="Actualizar tracking" variant="secondary" onPress={() => void load()}/><Button title="Volver" variant="secondary" onPress={() => router.back()}/></ScrollView></SafeAreaView>;
}
const useStyles = () => useThemedStyles(c => StyleSheet.create({ root:{flex:1,backgroundColor:c.bg}, content:{padding:spacing.md,gap:12}, title:{fontSize:25,fontWeight:'800',color:c.text}, section:{fontSize:17,fontWeight:'800',color:c.text}, state:{fontSize:18,fontWeight:'800',color:c.accentText}, provider:{fontWeight:'700',color:c.text}, text:{color:c.muted}, step:{borderLeftWidth:2,borderLeftColor:c.primary,paddingLeft:9,gap:2}, stepTitle:{fontWeight:'800',color:c.text} }));
