import { useCallback, useEffect, useState } from 'react';
import { Alert, FlatList, Image, Modal, Pressable, RefreshControl, ScrollView, StyleSheet, Text, View } from 'react-native';
import { router } from 'expo-router';
import { Button, Card, EmptyState, Input, Loading } from '@/components/ui';
import { colors, spacing } from '@/constants/theme';
import type { Product } from '@/models';
import { apiError } from '@/services/api';
import { b2bService } from '@/services/b2b.service';
import { storage } from '@/services/storage';

type CartItem = { idProducto:number; name:string; detail:string; qty:number; precioReferencia?:number|null; categoria?:string; marca?:string };
export default function Catalog() {
  const [products,setProducts]=useState<Product[]>([]),[cart,setCart]=useState<CartItem[]>([]),[filters,setFilters]=useState<any>({categorias:[],marcas:[]});
  const [categories,setCategories]=useState<number[]>([]),[brands,setBrands]=useState<number[]>([]),[priceMin,setPriceMin]=useState(''),[priceMax,setPriceMax]=useState(''),[search,setSearch]=useState('');
  const [priority,setPriority]=useState<'BALANCEADO'|'PRECIO'|'TIEMPO'>('BALANCEADO'),[showFilters,setShowFilters]=useState(false),[showCart,setShowCart]=useState(false),[loading,setLoading]=useState(true),[matching,setMatching]=useState(false);
  const load=useCallback(async()=>{setLoading(true);try{const [catalog,available,saved]=await Promise.all([b2bService.catalog({categorias:categories.length?categories:null,marcas:brands.length?brands:null,precioMin:priceMin?Number(priceMin):null,precioMax:priceMax?Number(priceMax):null,especificaciones:[]}),b2bService.productFilters(),storage.getCart<CartItem>()]);setProducts(catalog||[]);setFilters(available||{categorias:[],marcas:[]});setCart(saved||[]);}catch(e){Alert.alert('No se pudo cargar el catalogo',apiError(e));}finally{setLoading(false);}},[categories,brands,priceMin,priceMax]);
  useEffect(()=>{void load();},[load]);
  const visible=products.filter(p=>[p.producto,p.nombre,p.marca,p.categoria,p.descripcion].filter(Boolean).join(' ').toLowerCase().includes(search.trim().toLowerCase()));
  const toggle=(id:number,source:number[],update:(value:number[])=>void)=>update(source.includes(id)?source.filter(x=>x!==id):[...source,id]);
  const saveCart=async(next:CartItem[])=>{setCart(next);await storage.setCart(next);};
  const add=async(p:Product)=>{const id=Number(p.idProducto||p.id);if(!id)return;const old=cart.find(x=>x.idProducto===id);await saveCart(old?cart.map(x=>x.idProducto===id?{...x,qty:x.qty+1}:x):[...cart,{idProducto:id,name:p.producto||p.nombre||'Producto',detail:[p.marca,p.categoria].filter(Boolean).join(' - '),qty:1,precioReferencia:p.precioUnitario||p.precio||null,categoria:p.categoria,marca:p.marca}]);};
  const apply=()=>{const min=Number(priceMin||0),max=Number(priceMax||0);if(min&&max&&min>max)return Alert.alert('Rango invalido','El precio minimo no puede superar el maximo.');setShowFilters(false);};
  const find=async()=>{if(!cart.length)return Alert.alert('Solicitud vacia','Agrega al menos un producto al RFQ.');setMatching(true);try{const providers=await b2bService.rfqMatches({items:cart.map(x=>({idProducto:x.idProducto,cantidad:x.qty})),filtro:{marcas:brands,categorias:categories,precioMin:priceMin?Number(priceMin):null,precioMax:priceMax?Number(priceMax):null},prioridad:priority});await storage.setSelectedProvider({providers,cart,priority});router.push('/rfq-results');}catch(e){Alert.alert('No se encontraron proveedores',apiError(e));}finally{setMatching(false);}};
  if(loading)return <Loading/>;
  return <View style={s.root}><FlatList data={visible} keyExtractor={(p,i)=>String(p.idProducto||p.id||i)} contentContainerStyle={s.list} refreshControl={<RefreshControl refreshing={loading} onRefresh={load}/>} ListHeaderComponent={<><View style={s.hero}><Text style={s.eyebrow}>MARKETPLACE B2B</Text><Text style={s.heroTitle}>Encuentra tecnologia para tu empresa</Text><Text style={s.heroCopy}>Toca un producto para ver sus proveedores y resenas.</Text></View><Input label="Buscar en catalogo" value={search} onChangeText={setSearch} placeholder="Producto, marca o categoria"/><Button title="Filtros" variant="secondary" onPress={()=>setShowFilters(true)}/></>} ListEmptyComponent={<EmptyState title="No encontramos productos" detail="Cambia la busqueda o limpia los filtros."/>} renderItem={({item})=>{const image=item.imagenes?.find(x=>x.principal)?.url||item.imagenes?.[0]?.url;return <Card style={s.product}><Pressable style={s.productTap} onPress={()=>router.push({pathname:'/reviews',params:{productId:String(item.idProducto||item.id),product:String(item.producto||item.nombre||'Producto')}})}>{image?<Image source={{uri:image}} style={s.image}/>:<View style={s.placeholder}><Text style={s.placeholderText}>Producto</Text></View>}<View style={s.info}><Text style={s.name}>{item.producto||item.nombre||'Producto'}</Text><Text style={s.meta}>{[item.marca,item.categoria].filter(Boolean).join(' - ')||'Catalogo B2B'}</Text><Text style={s.price}>{item.precioUnitario||item.precio?`S/ ${Number(item.precioUnitario||item.precio).toFixed(2)}`:'Cotizar precio'}</Text></View></Pressable><Button title="Agregar al RFQ" variant="secondary" onPress={()=>void add(item)}/></Card>;}}/><Pressable style={s.fab} onPress={()=>setShowCart(true)}><Text style={s.fabText}>RFQ ({cart.reduce((n,x)=>n+x.qty,0)})</Text></Pressable>
  <Modal visible={showFilters} animationType="slide" onRequestClose={()=>setShowFilters(false)}><ScrollView style={s.modal} contentContainerStyle={s.modalContent}><Text style={s.modalTitle}>Filtros del catalogo</Text><Text style={s.group}>Rango de precio</Text><Input label="Precio minimo" keyboardType="decimal-pad" value={priceMin} onChangeText={setPriceMin} placeholder="0.00"/><Input label="Precio maximo" keyboardType="decimal-pad" value={priceMax} onChangeText={setPriceMax} placeholder="Sin limite"/><Text style={s.group}>Categorias</Text>{(filters.categorias||[]).map((x:any)=>{const id=Number(x.idCategoria??x.id);return <Pressable key={id} style={[s.option,categories.includes(id)&&s.optionActive]} onPress={()=>toggle(id,categories,setCategories)}><Text style={s.optionText}>{x.nombre||x.categoria}</Text></Pressable>;})}<Text style={s.group}>Marcas</Text>{(filters.marcas||[]).map((x:any)=>{const id=Number(x.idMarca??x.id);return <Pressable key={id} style={[s.option,brands.includes(id)&&s.optionActive]} onPress={()=>toggle(id,brands,setBrands)}><Text style={s.optionText}>{x.nombre||x.marca}</Text></Pressable>;})}<Button title="Aplicar filtros" onPress={apply}/><Button title="Limpiar filtros" variant="secondary" onPress={()=>{setCategories([]);setBrands([]);setPriceMin('');setPriceMax('');}}/></ScrollView></Modal>
  <Modal visible={showCart} animationType="slide" onRequestClose={()=>setShowCart(false)}><ScrollView style={s.modal} contentContainerStyle={s.modalContent}><Text style={s.modalTitle}>Tu solicitud RFQ</Text>{cart.length?cart.map(x=><Card key={x.idProducto}><Text style={s.name}>{x.name}</Text><Text style={s.meta}>{x.detail} - Cantidad: {x.qty}</Text><View style={s.controls}><Button title="-" variant="secondary" onPress={()=>void saveCart(x.qty===1?cart.filter(y=>y.idProducto!==x.idProducto):cart.map(y=>y.idProducto===x.idProducto?{...y,qty:y.qty-1}:y))}/><Button title="+" variant="secondary" onPress={()=>void saveCart(cart.map(y=>y.idProducto===x.idProducto?{...y,qty:y.qty+1}:y))}/></View></Card>):<EmptyState title="Aun no agregas productos" detail="Explora el catalogo para preparar una cotizacion."/>}<Text style={s.group}>Prioridad</Text>{(['BALANCEADO','PRECIO','TIEMPO']as const).map(x=><Pressable key={x} style={[s.option,priority===x&&s.optionActive]} onPress={()=>setPriority(x)}><Text style={s.optionText}>{x==='BALANCEADO'?'Mejor equilibrio':x==='PRECIO'?'Mejor precio':'Entrega rapida'}</Text></Pressable>)}<Button title="Buscar proveedores" loading={matching} onPress={()=>void find()}/><Button title="Seguir explorando" variant="secondary" onPress={()=>setShowCart(false)}/></ScrollView></Modal></View>;
}
const s=StyleSheet.create({root:{flex:1,backgroundColor:colors.bg},list:{padding:spacing.md,paddingBottom:90,gap:12},hero:{backgroundColor:colors.navy,padding:spacing.lg,borderRadius:8,gap:6},eyebrow:{fontSize:12,fontWeight:'800',color:colors.primaryLight},heroTitle:{fontSize:24,fontWeight:'800',color:'#fff'},heroCopy:{color:'#dbeafe'},product:{gap:10},productTap:{flexDirection:'row',gap:12},image:{width:88,height:88,borderRadius:8,backgroundColor:colors.surfaceSoft},placeholder:{width:88,height:88,borderRadius:8,backgroundColor:colors.surfaceSoft,justifyContent:'center',alignItems:'center'},placeholderText:{color:colors.muted,fontSize:12},info:{flex:1,gap:5},name:{fontSize:16,fontWeight:'800',color:colors.text},meta:{color:colors.muted,fontSize:13},price:{fontWeight:'800',color:colors.primaryDark},fab:{position:'absolute',right:20,bottom:20,backgroundColor:colors.primary,paddingVertical:14,paddingHorizontal:18,borderRadius:8,elevation:4},fabText:{color:'#fff',fontWeight:'800'},modal:{flex:1,backgroundColor:colors.bg},modalContent:{padding:spacing.lg,gap:12},modalTitle:{fontSize:24,fontWeight:'800',color:colors.navy},group:{fontSize:16,fontWeight:'800',color:colors.text,marginTop:8},option:{padding:13,borderWidth:1,borderColor:colors.border,borderRadius:8,backgroundColor:colors.surface},optionActive:{borderColor:colors.primary,backgroundColor:'#eff6ff'},optionText:{color:colors.text,fontWeight:'600'},controls:{flexDirection:'row',gap:8}});
